### ISSUE TITLE
MethodError: no method matching format_file(::String; overwrite=true, indent=4, margin=92, always_for_in=true, whitespace_typedefs=false, whitespace_ops_in_indices=false)

### ISSUE THREAD

**Issue by kdheepak** [singularitti/vscode-julia-formatter#3]
```julia
[2019-12-27 10:37:52.365] [exthost] [error] [singularitti.vscode-julia-formatter] provider FAILED
[2019-12-27 10:37:52.365] [exthost] [error] Error: Command failed: /Users/USER/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia --compile=min -e 'using JuliaFormatter' -e 'format("/Users/USER/GitRepos/Repository/test/runtests.jl"; overwrite = true, indent = 4, margin = 92, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)'
ERROR: MethodError: no method matching format_file(::String; overwrite=true, indent=4, margin=92, always_for_in=true, whitespace_typedefs=false, whitespace_ops_in_indices=false)
Closest candidates are:
  format_file(::AbstractString; indent, margin, overwrite, verbose, always_for_in) at /Users/USER/.julia/packages/JuliaFormatter/wYlfJ/src/JuliaFormatter.jl:277 got unsupported keyword arguments "whitespace_typedefs", "whitespace_ops_in_indices"
Stacktrace:
 [1] kwerr(::NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}, ::Function, ::String) at error.jl:125
 [2] (::JuliaFormatter.var"#kw##format_file")(::NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}, ::typeof(format_file), ::String) at none:0
 [3] #format#63(::Base.Iterators.Pairs{Symbol,Integer,NTuple{6,Symbol},NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}}, ::typeof(format), ::Tuple{String}) at /Users/USER/.julia/packages/JuliaFormatter/wYlfJ/src/JuliaFormatter.jl:338
 [4] (::JuliaFormatter.var"#kw##format")(::NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}, ::typeof(format), ::Tuple{String}) at none:0
 [5] #format#64(::Base.Iterators.Pairs{Symbol,Integer,NTuple{6,Symbol},NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}}, ::typeof(format), ::String) at /Users/USER/.julia/packages/JuliaFormatter/wYlfJ/src/JuliaFormatter.jl:353
 [6] (::JuliaFormatter.var"#kw##format")(::NamedTuple{(:overwrite, :indent, :margin, :always_for_in, :whitespace_typedefs, :whitespace_ops_in_indices),Tuple{Bool,Int64,Int64,Bool,Bool,Bool}}, ::typeof(format), ::String) at none:0
 [7] top-level scope at none:1

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by kdheepak** [comment]
I figured out the problem. I had an older version of `JuliaFormatter` installed and `up` didn't update it because it some of `JuliaFormatter`'s dependencies could not be updated (I think ... I got no warnings or errors from Julia's package manager.). 

One way to resolve this would be to use a custom environment for running JuliaFormatter. 

https://github.com/singularitti/vscode-julia-formatter/blob/0a310ba7b9e46ab39268de2bc1222503366aa236/src/extension.ts#L63

You can use `julia --project="path/to/folder" --compile=${compile}` in the above line, where the folder contains a `Project.toml` file that describes the JuliaFormatter version supported.

**Comment by singularitti** [comment]
> I figured out the problem. I had an older version of `JuliaFormatter` installed and `up` didn't update it because it some of `JuliaFormatter`'s dependencies could not be updated (I think ... I got no warnings or errors from Julia's package manager.).
> 
> One way to resolve this would be to use a custom environment for running JuliaFormatter.
> 
> https://github.com/singularitti/vscode-julia-formatter/blob/0a310ba7b9e46ab39268de2bc1222503366aa236/src/extension.ts#L63
> 
> You can use `julia --project="path/to/folder" --compile=${compile}` in the above line, where the folder contains a `Project.toml` file that describes the JuliaFormatter version supported.

Let me have a try.

**Comment by singularitti** [comment]
Could you try the `env` branch @kdheepak? It is not perfect I think.

**Comment by singularitti** [comment]
Hey guys @kdheepak , the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?

**Comment by kdheepak** [comment]
I don't have vscode installed but I'll ask someone else to test!

**Comment by singularitti** [comment]
> I don't have vscode installed but I'll ask someone else to test!

No problem, this is just an update!
